#import numpy as np
# This is number 2 in Euler Project
'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
'''

# A function to list the fibonacci numbers up to n
def fibo(n):
    #num = 1
    lister = [1]
    num1 = 0
    num2 = 1

    while True:
        newnum = num1+num2
        if newnum >= n:
            break
        lister.append(newnum)
        num1 = num2
        num2 = newnum
        #num += 1
    
    print(lister)

fibo(14)
